// Init this project
var cms 			= 'wordpress'; 					// wordpress OR drupal
var domain			= 'westlandkaart.nl'; 					// i.e. occhio.nl
var dev_user		= 'westlandkaartnl'; 					// i.e. occhionl
var dev_domain		= domain + '.dev.occhio.nl'; 	// 'dev.' + domain OR domain + '.dev.occhio.nl';

// Environments
var local_domain	= 'local.' + domain;
var dev_path		= dev_user + '@' + dev_domain + ':/var/www/vhosts/' + domain + '/httpdocs';

// Load modules
var gulp 			= require('gulp');
var del 			= require('del');
var flatten 		= require('gulp-flatten');
var header 			= require('gulp-header');
var	rename 			= require('gulp-rename');
var rsync 			= require('rsyncwrapper').rsync;
var plumber			= require('gulp-plumber');
var	browserSync 	= require('browser-sync').create();
var sourcemaps 		= require('gulp-sourcemaps');
var	sass 			= require('gulp-sass');
var	sassGlob 		= require('gulp-sass-glob-import');
var urlAdjuster 	= require('gulp-css-url-adjuster');
var	autoprefixer 	= require('gulp-autoprefixer');
var	concat 			= require('gulp-concat');
var	uglify 			= require('gulp-uglify');
var imagemin 		= require('gulp-imagemin');
var svgmin 			= require('gulp-svgmin');
var taskListing 	= require('gulp-task-listing');

/*----------------------------------------------------*/

/**
 * Paths to project folders
 */
var paths = {
	all: {
		input: 'src/**/*',
		output: 'dist/'
	},
	scripts: {
		input: 	'src/js/**/*.js',
		output: 'dist/js/'
	},
	vendor: {
		input: 	'src/js/vendor/**/*.js',
		output: 'dist/js/'
	},
	styles: {
		input: 	'src/sass/**/*.{scss,sass}',
		output: 'dist/css/'
	},
	fonts: {
		input: 	'src/fonts/**/*',
		output: 'dist/fonts/'
	},
	svgs: {
		input: 	'src/svg/*',
		output: 'dist/svg/'
	},
	images: {
		input: 	'src/img/*',
		output: 'dist/img/'
	},
	cmsImages: {
		input: '../../uploads/**/*',
		backup:'../../uploads/backup-uploads/',
		output:'../../uploads/**/*'
	},
	php: {
		input: '**/*.php'
	}
};


/**
 * Template for banner to add to file headers
 * One for CSS and one for JS
 */
var banner = {
	full :
		'/*!\n' +
		" * DON'T EDIT THIS FILE!\n" +
		' * Generated by Gulp on ' + new Date().getFullYear() + '\n' +
		' * Occhio web developers\n' +
		' * http://www.occhio.nl/\n' +
		' * info@occhio.nl\n' +
		' * +31 (0)20 320 78 70\n\n' +
		' * http://www.occhio.nl/over-occhio/vacatures/' +
		' */\n\n'
};


/**
 * Create clean: tasks
 * These tasks remove pre-existing content from output folders specific to the folder that will be created
 */
for(var type in paths) {
	var oPath = paths[type];
	// only get the output paths
	if(typeof oPath == 'object' && typeof oPath.output != 'undefined') {
		// create task like clean:all, clean:images, etc
		gulp.task('clean:' + type, function () {
			return del.sync(oPath.output);
		});
	}
}

/**
 * backup uploads
 */
gulp.task('backup:uploads', function () {
	return gulp.src(paths.cmsImages.input)
		.pipe(gulp.dest(paths.cmsImages.backup))
});


/**
 * 	Compress images
 */
gulp.task('build:images', ['clean:images'], function() {
	return gulp.src(paths.images.input)
//		.pipe(imagemin())
		.pipe(gulp.dest(paths.images.output))
});

/**
 * 	Compress fonts
 */
gulp.task('build:fonts', ['clean:fonts'], function() {
	return gulp.src(paths.fonts.input)
//		TODO
		.pipe(gulp.dest(paths.fonts.output))
});

// specific for Wordpress (if you're using Drupal Change the path)
gulp.task('cms:images', ['backup:uploads'], function() {
	return gulp.src(paths.cmsImages.input)
		// .pipe(imagemin())
		// .pipe(gulp.dest(paths.cmsImages.output))
});

/**
 *  Compress SVG and Generate Sprites
 */
gulp.task('build:svgs', ['clean:svgs'], function () {
	return gulp.src(paths.svgs.input)
		.pipe(svgmin())
		.pipe(gulp.dest(paths.svgs.output))
});

/**
 * Compress and combine JS files (2 outputfiles -> vendor and app.js)
 */
gulp.task('build:scripts', ['clean:scripts'], function() {
	// array of scripts that should be generated
	var aScripts = [{
		// app.js
		filename: 'app.js',
		srcDir: paths.scripts.input,
		destDir: paths.scripts.output,
		exclude: paths.vendor.input
	}, {
		// vendor.js
		filename: 'vendor.js',
		srcDir: paths.vendor.input,
		destDir: paths.vendor.output,
		exclude: ''
	}];

	// loop scripts and run gulp tasks
	for(var i = 0; i < aScripts.length; i++) {
		// init script paths
		var oScript = aScripts[i];

		// run gulp task
		gulp.src([oScript.srcDir, '!' + oScript.exclude])
			.pipe(plumber())
			.pipe(sourcemaps.init())
			.pipe(header(banner.full))
			.pipe(concat(oScript.filename))
			.pipe(gulp.dest(oScript.destDir))
			.pipe(rename({ suffix: '.min' }))
			.pipe(uglify())
			.pipe(sourcemaps.write("./"))
			.pipe(gulp.dest(oScript.destDir));
	}

	// browser reload
	return browserSync.reload();
});

/**
 *  Browser sync
 */
gulp.task('serve', function() {
	browserSync.init({
		//proxy: local_domain
	});
});

/**
 * Process, lint, and minify Sass files
 * @todo sourcemaps breekt browsersync stream
 * @todo op het laatst pas oude CSS weggooien
 */
gulp.task('build:styles', ['clean:styles'], function() {
	return gulp.src(paths.styles.input)
		.pipe(plumber())
		.pipe(sourcemaps.init())
		.pipe(sassGlob())
		.pipe(sass({
			outputStyle: 'expanded',
			sourceComments: true
		}))
		.pipe(flatten())
		.pipe(autoprefixer({
			browsers: ['> 1%', 'last 3 versions']
		}))
		.pipe(urlAdjuster({
			prependRelative: '../img/',
			append: '?version=' + Date.now()
		}))
		.pipe(sourcemaps.write("./"))
		.pipe(gulp.dest(paths.styles.output))
		.pipe(browserSync.stream({match: '**/*.css'}));
});

/**
 * Build PHP
 */
gulp.task('build:php', function() {
	return browserSync.reload();
});

/************************************************
 * RSYNC
 ************************************************/

/**
 * Create sync paths
 */
if(cms == 'wordpress') {
	var syncPaths = {
		uploads: {
			'local' : '../../uploads/',
			'dev' : dev_path + '/wp-content/uploads/',
		},
		plugins: {
			'local' : '../../plugins/',
			'dev' : dev_path + '/wp-content/plugins/',
		},
		parentTheme: {
			'local' : '../occhio/',
			'dev' : dev_path + '/wp-content/themes/occhio/',
		}
	};
} else if(cms == 'drupal') {
	var syncPaths = {
		uploads: {
			'local' : '../../../default/files/',
			'dev' : dev_path + '/sites/default/files/'
		},
		modules: {
			'local' : '../../modules/',
			'dev' : dev_path + '/sites/all/modules/'
		}
	};
}

/**
 * Default rsync settings
 */
var rsyncSettings = {
	ssh: true,
	recursive: true,
	syncDest: true,
	args: ['--verbose']
}
var rsyncCallback = function(error, stdout, stderr, cmd) {
	console.log(stdout);
};

/**
 * loop all sync paths and create gulp tasks
 * call these like:
 * gulp sync:uploads
 * gulp sync:plugins (for wordpress)
 * gulp sync:modules (for drupal)
 * etc
 */
for(var key in syncPaths) {
	// dev to local
	gulp.task('sync:' + key, function() {
		var currentKey = this.seq[0].substr(this.seq[0].indexOf(':') + 1);
		rsyncSettings.src = syncPaths[currentKey].dev;
		rsyncSettings.dest = syncPaths[currentKey].local;
		console.log(rsyncSettings);
		rsync(rsyncSettings, rsyncCallback);
	});
}

/************************************************
 * MAIN TASKS
 ************************************************/

/**
 * Watch all
 */
gulp.task('watch', function() {
	gulp.watch(paths.php.input,		['build:php']);
	gulp.watch(paths.styles.input,	['build:styles']);
	gulp.watch(paths.vendor.input,	['build:scripts']);
	gulp.watch(paths.scripts.input,	['build:scripts']);
	gulp.watch(paths.svgs.input,	['build:svgs']);
	gulp.watch(paths.images.input,	['build:images']);
});

/**
 * Build all
 */
gulp.task('build', ['build:php','build:styles','build:scripts','build:svgs','build:images', 'build:fonts']);

/**
 * Build all and watch task at the beginning
 */
gulp.task('default', ['build', 'watch', 'serve']);

/**
 * Call gulp help to view all possible tasks of this gulp file
 */
gulp.task('help', taskListing);
